name: you_might_need_work
description: Task manager
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  reactive_forms_generator: ^4.3.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
   - .env
   - assets/images/
