// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, combinators_ordering, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKsvqmtCQ11YIInQjrnMgn2QrpzcAo98',
    appId: '1:109523644824:android:b2b97a8481809dd1ccbbed',
    messagingSenderId: '109523644824',
    projectId: 'mightneedwork',
    storageBucket: 'mightneedwork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCss-U2Le1AklJsHzNiickxxFXvkoBsztc',
    appId: '1:109523644824:ios:4754e9e57cccdd03ccbbed',
    messagingSenderId: '109523644824',
    projectId: 'mightneedwork',
    storageBucket: 'mightneedwork.appspot.com',
    androidClientId:
        '109523644824-03jma94jros1k6efk4mdf6btmlbkl7k3.apps.googleusercontent.com',
    iosClientId:
        '109523644824-ndhji8f388248qke0qjgim2ps28otc59.apps.googleusercontent.com',
    iosBundleId: 'com.queryblocks.youMightNeedWork',
  );
}
